# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'PassportMRZScanner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PassportMRZScanner
  pod 'DynamsoftLabelRecognizerBundle','3.2.3000'
  pod 'DynamsoftCodeParser','2.2.10'
  pod 'DynamsoftCodeParserDedicator','1.2.20'

end
